[package]
name = "gtk-test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#gtk = { version = "0.14.1", features = ["v3_22"] }
gtk = { version = "0.2", package = "gtk4" }
