[package]
name = "fltk-calculator"
version = "0.1.0"
edition = "2021"

[dependencies]
fltk-theme = "0.4.2"
calc_engine = "0.4.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.fltk]
version = "1.3.6"
#features = ["use-wayland"]
